import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useLenis } from "./_hooks/use-lenis";
import LenisProvider from './_hooks/use-lenis';
import { Header } from "./_components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Abdulrahman Nasser - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`min-h-[200vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider />
        <Header />
        {children}
      </body>
    </html>
  );
}
